name = "GeometricIntegratorsDiffEq"
uuid = "5a33fad7-5ce4-5983-9f5d-5f26ceab5c96"
version = "0.2.5"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
DiffEqBase = "6.62"
GeometricIntegrators = "0.15"
Reexport = "0.2, 1"
SciMLBase = "2"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "ODEProblemLibrary", "Test"]
