name = "GeometricIntegratorsDiffEq"
uuid = "5a33fad7-5ce4-5983-9f5d-5f26ceab5c96"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.0.2"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"
DiffEqBase = "6"
GeometricIntegrators = "0.1"
Reexport = "0.2"

[extras]
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqProblemLibrary", "Test"]
